name: tajwid_evaluation_app
description: A comparative study of ML classifiers for evaluating Quranic Tajwid rules on mobile devices.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  audio_session: ^0.1.13
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_sound: ^9.2.13
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  tflite_flutter: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/models/
    - assets/images/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf